/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Animal } from '../models/animal';
import { apiAnimalsGet } from '../fn/animals/api-animals-get';
import { ApiAnimalsGet$Params } from '../fn/animals/api-animals-get';
import { apiAnimalsIdDelete } from '../fn/animals/api-animals-id-delete';
import { ApiAnimalsIdDelete$Params } from '../fn/animals/api-animals-id-delete';
import { apiAnimalsIdGet } from '../fn/animals/api-animals-id-get';
import { ApiAnimalsIdGet$Params } from '../fn/animals/api-animals-id-get';
import { apiAnimalsIdPut } from '../fn/animals/api-animals-id-put';
import { ApiAnimalsIdPut$Params } from '../fn/animals/api-animals-id-put';
import { apiAnimalsPost } from '../fn/animals/api-animals-post';
import { ApiAnimalsPost$Params } from '../fn/animals/api-animals-post';

@Injectable({ providedIn: 'root' })
export class AnimalsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAnimalsGet()` */
  static readonly ApiAnimalsGetPath = '/api/animals';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAnimalsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAnimalsGet$Response(params?: ApiAnimalsGet$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Animal>>> {
    const obs = apiAnimalsGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAnimalsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAnimalsGet(params?: ApiAnimalsGet$Params, context?: HttpContext): Promise<Array<Animal>> {
    const resp = this.apiAnimalsGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Animal>>): Array<Animal> => r.body);
  }

  /** Path part for operation `apiAnimalsPost()` */
  static readonly ApiAnimalsPostPath = '/api/animals';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAnimalsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiAnimalsPost$Response(params: ApiAnimalsPost$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiAnimalsPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAnimalsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiAnimalsPost(params: ApiAnimalsPost$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiAnimalsPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiAnimalsIdGet()` */
  static readonly ApiAnimalsIdGetPath = '/api/animals/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAnimalsIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAnimalsIdGet$Response(params: ApiAnimalsIdGet$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiAnimalsIdGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAnimalsIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAnimalsIdGet(params: ApiAnimalsIdGet$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiAnimalsIdGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiAnimalsIdPut()` */
  static readonly ApiAnimalsIdPutPath = '/api/animals/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAnimalsIdPut()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiAnimalsIdPut$Response(params: ApiAnimalsIdPut$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiAnimalsIdPut(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAnimalsIdPut$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiAnimalsIdPut(params: ApiAnimalsIdPut$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiAnimalsIdPut$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiAnimalsIdDelete()` */
  static readonly ApiAnimalsIdDeletePath = '/api/animals/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAnimalsIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAnimalsIdDelete$Response(params: ApiAnimalsIdDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiAnimalsIdDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAnimalsIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAnimalsIdDelete(params: ApiAnimalsIdDelete$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiAnimalsIdDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
