/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AnonymousTypeOfstringAndstring } from '../models/anonymous-type-ofstring-andstring';
import { get } from '../fn/api/get';
import { Get$Params } from '../fn/api/get';

@Injectable({ providedIn: 'root' })
export class ApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `get()` */
  static readonly GetPath = '/';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params?: Get$Params, context?: HttpContext): Promise<StrictHttpResponse<AnonymousTypeOfstringAndstring>> {
    const obs = get(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params?: Get$Params, context?: HttpContext): Promise<AnonymousTypeOfstringAndstring> {
    const resp = this.get$Response(params, context);
    return resp.then((r: StrictHttpResponse<AnonymousTypeOfstringAndstring>): AnonymousTypeOfstringAndstring => r.body);
  }

}
