/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Get$Params as Get$Params } from './fn/api/get';
export { get as get } from './fn/api/get';
export type { ApiAnimalsGet$Params as ApiAnimalsGet$Params } from './fn/animals/api-animals-get';
export { apiAnimalsGet as apiAnimalsGet } from './fn/animals/api-animals-get';
export type { ApiAnimalsPost$Params as ApiAnimalsPost$Params } from './fn/animals/api-animals-post';
export { apiAnimalsPost as apiAnimalsPost } from './fn/animals/api-animals-post';
export type { ApiAnimalsIdGet$Params as ApiAnimalsIdGet$Params } from './fn/animals/api-animals-id-get';
export { apiAnimalsIdGet as apiAnimalsIdGet } from './fn/animals/api-animals-id-get';
export type { ApiAnimalsIdPut$Params as ApiAnimalsIdPut$Params } from './fn/animals/api-animals-id-put';
export { apiAnimalsIdPut as apiAnimalsIdPut } from './fn/animals/api-animals-id-put';
export type { ApiAnimalsIdDelete$Params as ApiAnimalsIdDelete$Params } from './fn/animals/api-animals-id-delete';
export { apiAnimalsIdDelete as apiAnimalsIdDelete } from './fn/animals/api-animals-id-delete';
