/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Animal } from './models/animal';
export type { AnonymousTypeOfstringAndstring } from './models/anonymous-type-ofstring-andstring';
export type { CreateAnimalRequest } from './models/create-animal-request';
export type { UpdateAnimalRequest } from './models/update-animal-request';
